### ISSUE TITLE
Unable to open two datasets

### ISSUE THREAD

**Issue by cheukhin1024** [EY-Data-Science-Program/2022-Better-Working-World-Data-Challenge#2]
When I click
 [Training Dataset Summary](https://github.com/EY-Data-Science-Program/2022-Better-Working-World-Data-Challenge/blob/accc61893f829d5dffdce0a2763234ddb8f42766/notebooks/level_1_challenge/supplementary_notebooks/dataset_summary.ipynb)
[TerraClimate/Weather](https://github.com/EY-Data-Science-Program/2022-Better-Working-World-Data-Challenge/blob/accc61893f829d5dffdce0a2763234ddb8f42766/notebooks/level_1_challenge/supplementary_notebooks/TerraClimate.ipynb)

,I cannot open it.

Web page: https://github.com/EY-Data-Science-Program/2022-Better-Working-World-Data-Challenge/blob/main/notebooks/level_1_challenge/challenge_1_benchmark.ipynb

**Comment by BillyDodds** [comment]
Hi Christophe, 

The notebooks are quite large, so GitHub struggles to render them. It usually works if you refresh the webpage a few times, but the best way to read them is on JupyterHub (or another iPython editor) once you have set up an environment. 

Hope this helps! 
Billy

**Comment by BillyDodds** [comment]
Thanks, [Christophe](https://github.com/cheukhin1024). These links are now fixed.
